#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH

console_redirect() {
        if [ -c "$1" ]; then
                exec <$1 &>$1
        fi
}

[ -d /dev ] || mkdir -m 0755 /dev
[ -d /dev/pts ] || mkdir /dev/pts
mkdir -p /proc /sys /etc /run /tmp /var/log

echo "  mounting devfs..."
if ! mount -t devtmpfs -o mode=0755 udev /dev; then
        mount -t tmpfs -o mode=0755 udev /dev
        [ -e /dev/console ] || mknod /dev/console c 5 1
        [ -e /dev/null ] || mknod /dev/null c 1 3
fi

console_redirect /dev/console

printf "\n\nMinimal init is starting up...\n"

echo "  mounting proc..."
mount -t proc -o nodev,noexec,nosuid proc /proc

echo 1 1 1 1 > /proc/sys/kernel/printk

echo "  mounting sysfs..."
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
echo "  mounting run/tmp..."
mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /tmp

echo "  mounting devpts..."
mkdir -p /dev/pts
mount -t devpts none /dev/pts

echo "Launching interactive shell..."
setsid cttyhack sh
